services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
  joomla:
    build: .
    ports:
      - "9002:8080"
    depends_on:
      - mysql
